In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [262]:
df = pd.read_csv('customer_behaviour.csv')

In [264]:
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.00,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.00,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.00,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.00,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.00,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly
5,3583,23,Female,Shorts,Clothing,41.00,California,S,Beige,Summer,3.4,No,2-Day Shipping,No,15.0,PayPal,Annually
6,1135,62,Male,T-shirt,Clothing,81.00,Wisconsin,M,Brown,Summer,NaN,No,Express,Yes,2.0,Venmo,Every 3 Months
7,1411,61,Male,Hat,Accessories,93.00,Tennessee,M,Purple,Summer,4.0,No,Store Pickup,Yes,18.0,Debit Card,Annually
8,113,37,Male,Gloves,Accessories,65.00,Florida,M,Red,Spring,4.3,Yes,Free Shipping,Yes,28.0,PayPal,Bi-Weekly
9,166,42,Male,Handbag,Accessories,60.00,Kentucky,S,Yellow,Winter,2.8,Yes,Store Pickup,Yes,7.0,Cash,Monthly
10,4568,35,Other,Shoes,Clothing,NaN,Phoenix,M,Blue,Autumn,NaN,No,Express,Yes,41.0,Credit Card,Monthly
11,947,46,Male,Coat,Outerwear,24.00,Pennsylvania,XL,Blue,Spring,2.8,Yes,Next Day Air,Yes,4.0,PayPal,Quarterly
12,4776,64,Other,Laptop,Electronics,884.04,Los Angeles,NaN,Black,Spring,NaN,No,Express,No,NaN,Credit Card,Quarterly
13,3855,57,Female,T-shirt,Clothing,20.00,Florida,M,Black,Spring,4.2,No,Free Shipping,No,4.0,Venmo,Annually
14,481,68,Male,Hoodie,Clothing,88.00,Vermont,M,Gray,Summer,4.8,Yes,Standard,Yes,30.0,Debit Card,Bi-Weekly
15,3790,56,Female,Shirt,Clothing,75.00,North Dakota,M,Magenta,Summer,3.8,No,Express,No,18.0,Bank Transfer,Every 3 Months
16,3617,42,Female,Hoodie,Clothing,23.00,Wisconsin,L,Purple,Winter,3.3,No,Store Pickup,No,33.0,Debit Card,Fortnightly
17,2659,52,Female,Handbag,Accessories,47.00,Ohio,XL,Indigo,Summer,3.2,No,Next Day Air,No,39.0,PayPal,Monthly
18,3725,30,Female,Gloves,Accessories,71.00,Colorado,L,Green,Winter,3.1,No,Express,No,18.0,Bank Transfer,Annually
19,2134,21,Male,Hat,Accessories,34.00,Maine,M,Olive,Summer,3.8,No,Standard,No,13.0,Bank Transfer,Annually
20,4256,70,Male,Phone,Electronics,NaN,Los Angeles,NaN,Green,Autumn,NaN,Yes,Standard,Yes,25.0,Cash,Weekly
21,833,58,Male,Jacket,Outerwear,80.00,California,L,Blue,Fall,2.5,Yes,Express,Yes,28.0,Cash,Bi-Weekly
22,1106,33,Male,T-shirt,Clothing,83.00,Massachusetts,S,Olive,Spring,3.0,No,Next Day Air,Yes,6.0,Venmo,Every 3 Months
23,3047,60,Female,Shoes,Footwear,49.00,Pennsylvania,M,White,Spring,3.2,No,Store Pickup,No,25.0,Cash,Every 3 Months
24,4685,68,Other,Phone,Clothing,1032.09,Phoenix,L,Black,Summer,NaN,No,Express,No,NaN,PayPal,Monthly
25,1612,41,Male,Pants,Clothing,26.00,Arkansas,L,Yellow,Winter,4.5,No,Next Day Air,Yes,6.0,Debit Card,Monthly
26,4289,34,Female,Phone,Accessories,1282.44,New York,S,Red,Autumn,NaN,No,Express,Yes,36.0,PayPal,Weekly
27,3552,66,Female,Gloves,Accessories,31.00,Montana,L,Black,Spring,2.6,No,Store Pickup,No,20.0,Venmo,Weekly
28,2918,58,Female,Shirt,Clothing,45.00,Colorado,XL,White,Winter,2.9,No,Store Pickup,No,50.0,Venmo,Annually
29,1192,34,Male,T-shirt,Clothing,70.00,Indiana,L,Charcoal,Winter,4.1,No,Free Shipping,Yes,50.0,Venmo,Quarterly
30,1907,23,Male,Backpack,Accessories,30.00,Vermont,M,Green,Spring,4.6,No,2-Day Shipping,No,24.0,PayPal,Fortnightly
31,1332,38,Male,Socks,Clothing,91.00,Maryland,M,Lavender,Spring,3.2,No,Standard,Yes,8.0,PayPal,Bi-Weekly
32,316,66,Male,Jewelry,Accessories,24.00,Wisconsin,XL,Orange,Spring,4.5,Yes,Express,Yes,24.0,Debit Card,Annually
33,347,49,Male,Jeans,Clothing,50.00,New Mexico,L,Violet,Spring,4.7,Yes,Next Day Air,Yes,5.0,Cash,Weekly
34,3115,21,Female,Handbag,Accessories,56.00,Arkansas,M,Olive,Spring,4.7,No,Store Pickup,No,45.0,Venmo,Bi-Weekly
35,5042,46,Other,Bag,Clothing,NaN,Los Angeles,M,White,Summer,NaN,Yes,Express,No,31.0,PayPal,Monthly
36,1498,69,Male,Jacket,Outerwear,33.00,Michigan,S,Magenta,Spring,3.8,No,2-Day Shipping,Yes,16.0,Debit Card,Every 3 Months
37,1606,70,Male,Belt,Accessories,46.00,Connecticut,M,Lavender,Winter,3.4,No,Next Day Air,Yes,15.0,Credit Card,Bi-Weekly
38,4418,67,Female,Watch,Electronics,NaN,Los Angeles,NaN,Red,Autumn,NaN,No,Express,No,47.0,PayPal,Quarterly
39,4894,24,Other,Bag,Accessories,NaN,Los Angeles,L,Red,Spring,NaN,No,Standard,No,4.0,PayPal,Quarterly
40,4576,65,Male,Headphones,Accessories,NaN,New York,S,Black,Summer,NaN,No,Standard,Yes,47.0,Cash,Weekly
41,2486,43,Male,Blouse,Clothing,55.00,Louisiana,M,Beige,Spring,4.6,No,2-Day Shipping,No,37.0,Bank Transfer,Annually
42,187,39,Male,Backpack,Accessories,56.00,Minnesota,S,Lavender,Summer,2.9,Yes,Standard,Yes,31.0,Debit Card,Annually
43,275,59,Male,Jewelry,Accessories,32.00,Maryland,M,Indigo,Spring,3.0,Yes,Express,Yes,28.0,Cash,Bi-Weekly
44,1402,23,Male,Sandals,Footwear,59.00,Indiana,M,Blue,Fall,3.5,No,2-Day Shipping,Yes,1.0,PayPal,Weekly
45,1181,23,Male,Skirt,Clothing,23.00,Oregon,S,Beige,Spring,4.9,No,Standard,Yes,34.0,Cash,Monthly
46,2130,40,Male,Skirt,Clothing,57.00,Minnesota,L,Orange,Fall,2.8,No,Store Pickup,No,12.0,PayPal,Every 3 Months
47,995,53,Male,Shoes,Footwear,68.00,New York,L,Violet,Fall,3.2,Yes,Express,Yes,20.0,Debit Card,Monthly
48,1230,34,Male,Jewelry,Accessories,52.00,Kansas,XL,Maroon,Winter,3.6,No,Express,Yes,39.0,Bank Transfer,Annually
49,4319,47,Other,Watch,Electronics,NaN,Houston,NaN,Green,Summer,NaN,Yes,Express,Yes,28.0,PayPal,Monthly
50,4489,36,Female,Phone,Accessories,748.61,Los Angeles,L,Red,Summer,NaN,No,Express,No,0.0,PayPal,Monthly
51,4708,33,Female,Bag,Electronics,NaN,New York,NaN,Green,Winter,4.0,Yes,Standard,Yes,31.0,Debit Card,Quarterly
52,4827,20,Female,Laptop,Electronics,NaN,Houston,NaN,Green,Summer,NaN,No,Express,No,17.0,Debit Card,Monthly
53,1348,44,Male,Sweater,Clothing,95.00,Vermont,M,Cyan,Summer,3.9,No,2-Day Shipping,Yes,47.0,Bank Transfer,Monthly
54,4584,55,Female,Watch,Clothing,NaN,New York,M,Black,Autumn,5.0,No,Express,Yes,NaN,Debit Card,Quarterly
55,3116,26,Female,Scarf,Accessories,53.00,South Dakota,M,Charcoal,Fall,4.1,No,Free Shipping,No,9.0,Bank Transfer,Bi-Weekly
56,1168,60,Male,Socks,Clothing,83.00,New Jersey,XL,Beige,Summer,3.6,No,Free Shipping,Yes,16.0,PayPal,Quarterly
57,3685,29,Female,Skirt,Clothing,86.00,Pennsylvania,L,Charcoal,Spring,4.4,No,Free Shipping,No,47.0,Credit Card,Bi-Weekly
58,4111,49,Male,Phone,Clothing,NaN,Houston,M,Black,Summer,NaN,No,Express,No,NaN,PayPal,Weekly
59,2850,56,Female,Coat,Outerwear,25.00,New Hampshire,M,Gold,Spring,4.1,No,Express,No,27.0,PayPal,Bi-Weekly
60,1636,68,Male,Sunglasses,Accessories,24.00,North Carolina,L,Violet,Summer,3.2,No,Standard,Yes,40.0,Cash,Annually
61,1489,23,Male,Hat,Accessories,44.00,Hawaii,L,Pink,Winter,4.0,No,Standard,Yes,37.0,Credit Card,Weekly
62,3827,50,Female,Jacket,Outerwear,31.00,Montana,M,Gray,Summer,4.0,No,Express,No,25.0,Bank Transfer,Annually
63,2417,59,Male,Sandals,Footwear,83.00,Nebraska,S,Black,Summer,4.0,No,Next Day Air,No,26.0,Credit Card,Every 3 Months
64,2832,34,Female,Hoodie,Clothing,53.00,Virginia,L,Pink,Winter,5.0,No,Express,No,4.0,Credit Card,Weekly
65,4607,47,Other,Shirt,Clothing,557.24,Los Angeles,L,White,Autumn,NaN,No,Express,Yes,27.0,PayPal,Weekly
66,2367,30,Male,Shoes,Footwear,66.00,New Mexico,L,Brown,Winter,3.6,No,Express,No,32.0,Credit Card,Fortnightly
67,4851,42,Female,Watch,Accessories,NaN,Chicago,L,Blue,Autumn,NaN,No,Standard,Yes,NaN,Cash,Weekly
68,508,65,Male,Shorts,Clothing,20.00,Maine,M,Magenta,Spring,5.0,Yes,Store Pickup,Yes,33.0,Debit Card,Fortnightly
69,4845,19,Female,Shirt,Accessories,692.11,New York,M,Red,Summer,NaN,No,Express,Yes,41.0,Debit Card,Weekly
70,2098,33,Male,Sneakers,Footwear,43.00,Iowa,S,Cyan,Winter,3.9,No,Next Day Air,No,5.0,Credit Card,Weekly
71,1080,18,Male,Coat,Outerwear,33.00,Oklahoma,S,Blue,Summer,4.4,No,Free Shipping,Yes,48.0,Bank Transfer,Monthly
72,4558,41,Other,Bag,Accessories,208.02,Los Angeles,M,White,Autumn,NaN,No,Standard,Yes,NaN,PayPal,Monthly
73,4492,59,Female,Laptop,Clothing,NaN,Phoenix,M,Green,Spring,1.0,Yes,Standard,Yes,38.0,Debit Card,Weekly
74,4292,27,Other,Laptop,Electronics,NaN,Houston,NaN,Blue,Summer,NaN,Yes,Express,Yes,NaN,Credit Card,Weekly
75,3036,69,Female,Handbag,Accessories,64.00,Kentucky,M,Gold,Spring,4.5,No,Free Shipping,No,18.0,Cash,Bi-Weekly
76,3554,62,Female,Shoes,Footwear,99.00,Minnesota,M,Charcoal,Spring,4.9,No,Free Shipping,No,32.0,Bank Transfer,Weekly
77,2077,59,Male,Gloves,Accessories,23.00,Florida,S,Indigo,Fall,4.6,No,Free Shipping,No,22.0,Debit Card,Bi-Weekly
78,3088,62,Female,Shirt,Clothing,84.00,North Carolina,M,Charcoal,Spring,3.1,No,Free Shipping,No,29.0,Bank Transfer,Monthly
79,3739,34,Female,Shorts,Clothing,45.00,Delaware,M,Brown,Spring,2.7,No,Free Shipping,No,48.0,Cash,Fortnightly
80,3309,55,Female,Jeans,Clothing,70.00,Utah,M,Pink,Fall,2.6,No,Express,No,29.0,Cash,Monthly
81,2922,20,Female,Handbag,Accessories,24.00,Wisconsin,M,Cyan,Fall,4.6,No,Standard,No,11.0,Cash,Fortnightly
82,4156,51,Other,Shirt,Clothing,1398.90,Chicago,XL,Red,Summer,2.0,Yes,Express,No,7.0,PayPal,Monthly
83,4869,26,Female,Headphones,Accessories,500.30,Phoenix,M,Red,Winter,3.0,No,Express,No,NaN,PayPal,Monthly
84,660,62,Male,Shorts,Clothing,52.00,Virginia,S,Gold,Spring,3.6,Yes,2-Day Shipping,Yes,8.0,Cash,Weekly
85,3632,48,Female,Hat,Accessories,50.00,New Jersey,M,Peach,Fall,2.9,No,Store Pickup,No,26.0,Credit Card,Monthly
86,3217,39,Female,Hoodie,Clothing,85.00,Illinois,S,Olive,Winter,3.4,No,Next Day Air,No,18.0,Cash,Weekly
87,3696,38,Female,Skirt,Clothing,33.00,Florida,M,White,Fall,4.6,No,Standard,No,18.0,Bank Transfer,Fortnightly
88,146,24,Male,Jewelry,Accessories,95.00,Missouri,M,Teal,Fall,4.5,Yes,Standard,Yes,44.0,Debit Card,Quarterly
89,693,35,Male,Sunglasses,Accessories,95.00,North Dakota,M,Cyan,Spring,4.0,Yes,2-Day Shipping,Yes,40.0,Debit Card,Every 3 Months
90,1837,66,Male,Pants,Clothing,52.00,South Carolina,M,Teal,Fall,4.2,No,2-Day Shipping,No,35.0,Credit Card,Monthly
91,598,70,Male,Jewelry,Accessories,69.00,Alaska,L,Gold,Summer,3.4,Yes,Standard,Yes,19.0,Bank Transfer,Fortnightly
92,165,59,Male,Handbag,Accessories,65.00,Delaware,S,Purple,Spring,2.6,Yes,Free Shipping,Yes,5.0,Credit Card,Fortnightly
93,1186,47,Male,Jeans,Clothing,64.00,Maine,M,Magenta,Spring,3.9,No,Standard,Yes,29.0,Credit Card,Monthly
94,3328,47,Female,Shorts,Clothing,64.00,Connecticut,M,Black,Spring,4.1,No,Express,No,2.0,Debit Card,Quarterly
95,4404,67,Male,Watch,Clothing,498.03,New York,XL,Blue,Winter,NaN,Yes,Standard,Yes,20.0,Debit Card,Monthly
96,4153,67,Other,Shoes,Accessories,NaN,Los Angeles,M,Red,Spring,NaN,No,Express,No,31.0,Credit Card,Monthly
97,4587,52,Male,Laptop,Electronics,1392.02,Phoenix,NaN,White,Winter,2.0,Yes,Standard,Yes,NaN,Cash,Quarterly
98,4057,41,Female,Shoes,Electronics,NaN,Los Angeles,NaN,Black,Winter,NaN,No,Standard,Yes,10.0,Credit Card,Quarterly
99,3889,45,Female,Sneakers,Footwear,69.00,Virginia,M,Violet,Spring,3.4,No,Standard,No,14.0,Venmo,Bi-Weekly
100,106,69,Male,Backpack,Accessories,96.00,New York,M,Charcoal,Fall,3.6,Yes,Next Day Air,Yes,4.0,Bank Transfer,Annually
101,4176,23,Male,Shoes,Clothing,390.25,Chicago,XL,Black,Autumn,NaN,No,Standard,No,NaN,Credit Card,Weekly
102,63,30,Male,Sneakers,Footwear,21.00,Mississippi,S,Magenta,Spring,3.8,Yes,Free Shipping,Yes,31.0,Credit Card,Fortnightly
103,3455,55,Female,Handbag,Accessories,71.00,Louisiana,S,Lavender,Fall,4.6,No,Store Pickup,No,15.0,PayPal,Bi-Weekly
104,2500,52,Male,Hoodie,Clothing,73.00,Louisiana,L,Pink,Summer,3.1,No,Next Day Air,No,2.0,Cash,Quarterly
105,2136,34,Male,Sunglasses,Accessories,94.00,California,S,Yellow,Winter,4.6,No,Next Day Air,No,1.0,Debit Card,Every 3 Months
106,3584,52,Female,Blouse,Clothing,77.00,Arizona,L,Brown,Summer,2.7,No,Store Pickup,No,44.0,Credit Card,Every 3 Months
107,4118,18,Other,Shirt,Accessories,NaN,Phoenix,S,Black,Summer,3.0,Yes,Standard,No,NaN,Debit Card,Quarterly
108,2547,63,Male,Boots,Footwear,21.00,Texas,L,Gray,Summer,3.0,No,Express,No,4.0,Credit Card,Quarterly
109,4972,46,Other,Bag,Accessories,34.65,New York,M,White,Autumn,4.0,No,Express,Yes,3.0,Debit Card,Monthly
110,3365,50,Female,Scarf,Accessories,33.00,Oregon,M,Peach,Fall,3.2,No,Standard,No,7.0,Credit Card,Monthly
111,1637,58,Male,Boots,Footwear,22.00,North Dakota,L,Green,Fall,4.0,No,Free Shipping,Yes,49.0,Cash,Fortnightly
112,2000,39,Male,Socks,Clothing,89.00,Tennessee,L,Indigo,Winter,4.6,No,2-Day Shipping,No,26.0,Debit Card,Monthly
113,2603,65,Male,Coat,Outerwear,44.00,South Carolina,M,Black,Fall,2.9,No,Free Shipping,No,1.0,Venmo,Quarterly
114,2700,25,Female,Boots,Footwear,96.00,Utah,M,Violet,Fall,3.6,No,2-Day Shipping,No,49.0,Debit Card,Annually
115,4189,38,Male,Shoes,Accessories,1312.35,Los Angeles,M,Black,Autumn,4.0,Yes,Standard,Yes,NaN,Cash,Weekly
116,3371,30,Female,Belt,Accessories,31.00,Illinois,M,Charcoal,Summer,2.8,No,Store Pickup,No,46.0,Cash,Fortnightly
117,3599,23,Female,Hoodie,Clothing,76.00,Connecticut,XL,Purple,Spring,4.6,No,Store Pickup,No,19.0,Bank Transfer,Bi-Weekly
118,4072,63,Male,Shoes,Clothing,NaN,Los Angeles,S,Red,Autumn,1.0,No,Standard,Yes,NaN,Credit Card,Quarterly
119,1432,39,Male,Pants,Clothing,88.00,South Dakota,M,Cyan,Fall,2.9,No,Express,Yes,29.0,Venmo,Quarterly
120,2381,41,Male,Scarf,Accessories,66.00,Pennsylvania,M,Black,Fall,2.5,No,Next Day Air,No,36.0,PayPal,Fortnightly
121,2120,58,Male,Jewelry,Accessories,57.00,Nebraska,M,Indigo,Spring,3.5,No,Store Pickup,No,36.0,Venmo,Bi-Weekly
122,3502,53,Female,Shoes,Footwear,87.00,Nebraska,M,Silver,Fall,4.8,No,Standard,No,43.0,Bank Transfer,Weekly
123,3551,63,Female,Shoes,Footwear,74.00,West Virginia,S,Orange,Winter,4.8,No,Standard,No,32.0,Cash,Weekly
124,712,64,Male,Boots,Footwear,60.00,New Hampshire,M,Maroon,Spring,3.5,Yes,2-Day Shipping,Yes,13.0,Bank Transfer,Bi-Weekly
125,1337,23,Male,Sneakers,Footwear,85.00,Oregon,M,Charcoal,Spring,4.8,No,Store Pickup,Yes,44.0,Debit Card,Fortnightly
126,1047,40,Male,Sneakers,Footwear,22.00,Illinois,M,Magenta,Winter,4.2,Yes,Standard,Yes,12.0,Venmo,Annually
127,2225,18,Male,Gloves,Accessories,25.00,Nebraska,L,Charcoal,Winter,4.3,No,Standard,No,38.0,Cash,Quarterly
128,3525,69,Female,Pants,Clothing,74.00,Michigan,L,Silver,Summer,2.9,No,Free Shipping,No,30.0,Credit Card,Monthly
129,4530,20,Male,Watch,Electronics,532.49,New York,NaN,Black,Autumn,NaN,Yes,Standard,Yes,NaN,Debit Card,Monthly
130,3199,61,Female,Gloves,Accessories,94.00,Pennsylvania,L,Peach,Winter,2.8,No,Free Shipping,No,39.0,Debit Card,Weekly
131,70,48,Male,Belt,Accessories,70.00,Tennessee,S,Cyan,Summer,4.4,Yes,Express,Yes,5.0,Cash,Weekly
132,2721,55,Female,Scarf,Accessories,52.00,Maryland,M,Peach,Spring,2.8,No,Store Pickup,No,45.0,Bank Transfer,Quarterly
133,436,51,Male,Coat,Outerwear,28.00,Montana,XL,Olive,Winter,3.6,Yes,Next Day Air,Yes,42.0,Bank Transfer,Monthly
134,387,64,Male,Jewelry,Accessories,39.00,Louisiana,L,Brown,Spring,3.4,Yes,Express,Yes,40.0,PayPal,Quarterly
135,3867,58,Female,Hat,Accessories,32.00,Alaska,M,Beige,Winter,3.3,No,2-Day Shipping,No,33.0,Credit Card,Fortnightly
136,3358,41,Female,Hoodie,Clothing,67.00,Arkansas,M,Pink,Winter,3.5,No,Free Shipping,No,37.0,Credit Card,Monthly
137,608,47,Male,Hoodie,Clothing,23.00,Indiana,L,Purple,Fall,2.8,Yes,Next Day Air,Yes,44.0,Cash,Monthly
138,115,70,Male,Coat,Outerwear,95.00,Massachusetts,S,Blue,Summer,3.7,Yes,Store Pickup,Yes,9.0,Cash,Weekly
139,4712,60,Male,Laptop,Clothing,95.15,Chicago,S,Red,Summer,NaN,No,Standard,No,16.0,Cash,Monthly
140,5058,63,Other,Shirt,Electronics,1342.62,Los Angeles,NaN,Blue,Spring,4.0,Yes,Standard,Yes,NaN,PayPal,Quarterly
141,2568,19,Male,Sunglasses,Accessories,25.00,Michigan,XL,Gold,Spring,4.3,No,Store Pickup,No,24.0,Cash,Fortnightly
142,4381,53,Female,Watch,Clothing,NaN,Chicago,M,Blue,Summer,3.0,No,Express,Yes,NaN,PayPal,Monthly
143,4192,46,Other,Watch,Electronics,105.21,Houston,NaN,Green,Winter,NaN,Yes,Standard,Yes,NaN,PayPal,Monthly
144,235,20,Male,Gloves,Accessories,39.00,South Dakota,S,Silver,Summer,3.7,Yes,Next Day Air,Yes,24.0,Credit Card,Weekly
145,3699,25,Female,Skirt,Clothing,54.00,California,XL,Maroon,Spring,4.0,No,2-Day Shipping,No,4.0,Venmo,Annually
146,3215,53,Female,Skirt,Clothing,78.00,Washington,M,Yellow,Spring,3.1,No,Free Shipping,No,6.0,Debit Card,Annually
147,1876,63,Male,Boots,Footwear,71.00,Tennessee,M,Brown,Winter,3.9,No,Next Day Air,No,6.0,Credit Card,Quarterly
148,1625,38,Male,Sweater,Clothing,32.00,Florida,M,White,Winter,3.6,No,Free Shipping,Yes,40.0,PayPal,Every 3 Months
149,1396,47,Male,Scarf,Accessories,32.00,West Virginia,L,Turquoise,Spring,2.8,No,Next Day Air,Yes,40.0,PayPal,Bi-Weekly
150,9,26,Male,Coat,Outerwear,97.00,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,8.0,Venmo,Annually
151,2168,30,Male,Skirt,Clothing,48.00,Ohio,L,Green,Winter,4.9,No,Standard,No,33.0,Venmo,Fortnightly
152,749,35,Male,Hat,Accessories,39.00,South Dakota,L,Brown,Fall,3.9,Yes,Free Shipping,Yes,8.0,Bank Transfer,Quarterly
153,2507,57,Male,Dress,Clothing,82.00,New York,XL,Orange,Spring,4.4,No,Free Shipping,No,19.0,Venmo,Annually
154,1285,65,Male,Dress,Clothing,93.00,Arkansas,M,Black,Spring,3.9,No,Express,Yes,38.0,PayPal,Fortnightly
155,4047,49,Male,Watch,Electronics,NaN,Phoenix,NaN,White,Summer,5.0,Yes,Standard,No,NaN,Cash,Weekly
156,5014,60,Female,Shirt,Accessories,NaN,Phoenix,S,Green,Winter,2.0,Yes,Standard,Yes,44.0,Debit Card,Monthly
157,1195,50,Male,Hoodie,Clothing,46.00,New York,S,Teal,Winter,3.1,No,2-Day Shipping,Yes,6.0,Credit Card,Fortnightly
158,2013,48,Male,Jeans,Clothing,53.00,Nevada,L,Green,Fall,3.2,No,Store Pickup,No,5.0,Cash,Fortnightly
159,4076,57,Other,Watch,Clothing,NaN,Phoenix,M,White,Summer,2.0,No,Express,No,38.0,Credit Card,Weekly
160,2050,68,Male,Boots,Footwear,24.00,Rhode Island,L,Blue,Fall,2.7,No,Standard,No,15.0,Venmo,Annually
161,1306,31,Male,Pants,Clothing,56.00,Mississippi,XL,Peach,Spring,4.5,No,Express,Yes,2.0,PayPal,Every 3 Months
162,5024,38,Other,Bag,Electronics,NaN,Los Angeles,NaN,Green,Summer,NaN,Yes,Express,Yes,NaN,Debit Card,Quarterly
163,3170,35,Female,T-shirt,Clothing,59.00,Georgia,M,White,Fall,3.8,No,Free Shipping,No,3.0,Venmo,Weekly
164,1116,30,Male,Hat,Accessories,58.00,New York,S,Peach,Fall,4.0,No,2-Day Shipping,Yes,37.0,Cash,Weekly
165,2317,28,Male,Sneakers,Footwear,39.00,Montana,L,Yellow,Winter,3.8,No,Standard,No,7.0,Debit Card,Annually
166,728,62,Male,Sweater,Clothing,97.00,Arkansas,S,Gray,Winter,4.8,Yes,Next Day Air,Yes,37.0,Venmo,Every 3 Months
167,467,38,Male,Jeans,Clothing,24.00,Vermont,L,Turquoise,Winter,4.6,Yes,Free Shipping,Yes,25.0,PayPal,Weekly
168,4235,56,Other,Headphones,Clothing,NaN,New York,S,Red,Spring,NaN,Yes,Express,Yes,NaN,Debit Card,Quarterly
169,656,20,Male,Handbag,Accessories,36.00,Mississippi,S,Purple,Fall,3.1,Yes,Free Shipping,Yes,19.0,Venmo,Monthly
170,4542,28,Other,Shoes,Electronics,NaN,Houston,NaN,Red,Summer,NaN,Yes,Express,No,NaN,PayPal,Weekly
171,99,20,Male,Jeans,Clothing,67.00,New York,XL,Teal,Spring,2.6,Yes,Next Day Air,Yes,20.0,Bank Transfer,Annually
172,3681,22,Female,Sunglasses,Accessories,36.00,Iowa,S,Blue,Winter,2.9,No,Standard,No,30.0,Debit Card,Quarterly
173,3715,18,Female,Hat,Accessories,31.00,New York,S,Peach,Winter,3.9,No,Express,No,35.0,Credit Card,Weekly
174,2726,64,Female,Backpack,Accessories,99.00,Mississippi,S,Violet,Summer,2.7,No,Free Shipping,No,4.0,Debit Card,Annually
175,2544,27,Male,Scarf,Accessories,56.00,West Virginia,L,Peach,Spring,2.7,No,Next Day Air,No,30.0,PayPal,Bi-Weekly
176,2834,43,Female,Jeans,Clothing,56.00,Arkansas,M,Teal,Fall,3.3,No,Free Shipping,No,19.0,Cash,Monthly
177,1084,35,Male,Backpack,Accessories,97.00,Washington,L,Teal,Summer,3.3,No,Store Pickup,Yes,43.0,Cash,Weekly
178,2904,38,Female,Scarf,Accessories,39.00,Delaware,S,Teal,Spring,3.5,No,2-Day Shipping,No,24.0,Credit Card,Every 3 Months
179,964,21,Male,Boots,Footwear,63.00,South Carolina,L,Green,Spring,2.5,Yes,2-Day Shipping,Yes,14.0,Credit Card,Weekly

In [266]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [268]:
df.shape

(5050, 17)

In [270]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,5050.000000,5050.000000,4494.000000,4449.000000,4502.000000
mean,2519.570891,44.150495,144.765236,3.668195,25.221901
std,1470.402964,15.282328,275.590101,0.865357,14.521635
min,1.000000,18.000000,10.120000,1.000000,0.000000
25%,1252.250000,31.000000,41.000000,3.000000,13.000000
50%,2499.500000,44.000000,65.000000,3.700000,25.000000
75%,3740.750000,57.000000,89.000000,4.400000,38.000000
max,5099.000000,70.000000,1499.760000,5.000000,50.000000

In [272]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             5050 non-null   int64
 1   Age                     5050 non-null   int64
 2   Gender                  5050 non-null   object
 3   Item Purchased          5050 non-null   object
 4   Category                5050 non-null   object
 5   Purchase Amount (USD)   4494 non-null   float64
 6   Location                5050 non-null   object
 7   Size                    4680 non-null   object
 8   Color                   5050 non-null   object
 9   Season                  5050 non-null   object
 10  Review Rating           4449 non-null   float64
 11  Subscription Status     5050 non-null   object
 12  Shipping Type           5050 non-null   object
 13  Discount Applied        5050 non-null   object
 14  Previous Purchases      4502 non-null   float64
 15  Payment Method          5050 non-null   object
 16  Frequency of Purchases  5050 non-null   object
dtypes: float64(3), int64(2), object(12)
memory usage: 670.8+ KB

In [274]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

#DATA CLEANING

In [276]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [278]:
#get the distinct values in item purchased
df['Item Purchased'].unique()

array(['T-shirt', 'Sunglasses', 'Shirt', 'Gloves', 'Jewelry', 'Shorts',
       'Hat', 'Handbag', 'Shoes', 'Coat', 'Laptop', 'Hoodie', 'Phone',
       'Jacket', 'Pants', 'Backpack', 'Socks', 'Jeans', 'Bag', 'Belt',
       'Watch', 'Headphones', 'Blouse', 'Sandals', 'Skirt', 'Sweater',
       'Scarf', 'Sneakers', 'Boots', 'Dress'], dtype=object)

In [280]:
df['Category'].unique()

array(['Clothing', 'Accessories', 'Outerwear', 'Electronics', 'Footwear'],
      dtype=object)

In [282]:
#to display the whole records
pd.set_option('display.max_colwidth',None)
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [284]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories               [Sunglasses, Gloves, Jewelry, Hat, Handbag, Phone, Backpack, Belt, Bag, Headphones, Scarf, Watch, Shirt, Shoes, Laptop]
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone, Pants, Socks, Jeans, Bag, Blouse, Skirt, Sweater, Watch, Laptop, Dress, Headphones]
Electronics                                                                                 [Laptop, Phone, Watch, Bag, Shoes, Shirt, Headphones]
Footwear                                                                                                        [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                                                                          [Coat, Jacket]
Name: Item Purchased, dtype: object

In [286]:
#since one product is mapped to many categories we would correct the mapping
category_mapping = {
    'Sunglasses': 'Accessories',
    'Gloves': 'Accessories',
    'Jewelry': 'Accessories',
    'Hat': 'Accessories',
    'Handbag': 'Accessories',
    'Backpack': 'Accessories',
    'Belt': 'Accessories',
    'Scarf': 'Accessories',
    'Bag': 'Accessories',

    'T-shirt': 'Clothing',
    'Shirt': 'Clothing',
    'Shorts': 'Clothing',
    'Hoodie': 'Clothing',
    'Pants': 'Clothing',
    'Socks': 'Clothing',
    'Jeans': 'Clothing',
    'Blouse': 'Clothing',
    'Skirt': 'Clothing',
    'Sweater': 'Clothing',
    'Dress': 'Clothing',

    'Laptop': 'Electronics',
    'Phone': 'Electronics',
    'Watch': 'Electronics',
    'Headphones': 'Electronics',

    'Shoes': 'Footwear',
    'Sandals': 'Footwear',
    'Sneakers': 'Footwear',
    'Boots': 'Footwear',

    'Coat': 'Outerwear',
    'Jacket': 'Outerwear'
}

In [288]:
df['Category']= df['Item Purchased'].map(category_mapping)

In [290]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [292]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories                 [Sunglasses, Gloves, Jewelry, Hat, Handbag, Backpack, Bag, Belt, Scarf]
Clothing       [T-shirt, Shirt, Shorts, Hoodie, Pants, Socks, Jeans, Blouse, Skirt, Sweater, Dress]
Electronics                                                      [Laptop, Phone, Watch, Headphones]
Footwear                                                          [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                            [Coat, Jacket]
Name: Item Purchased, dtype: object

#Treating null values

In [295]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [297]:
df['Size'].unique()

array(['XL', 'M', 'L', 'S', nan], dtype=object)

In [299]:
df.groupby('Category')['Size'].unique()

Category
Accessories    [M, L, S, XL, nan]
Clothing       [XL, M, S, L, nan]
Electronics    [nan, L, S, M, XL]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [301]:
df.groupby('Item Purchased')['Size'].unique()

Item Purchased
Backpack           [M, S, L, XL]
Bag           [M, L, nan, XL, S]
Belt               [M, S, XL, L]
Blouse             [M, L, S, XL]
Boots              [L, M, XL, S]
Coat               [XL, M, S, L]
Dress              [XL, M, L, S]
Gloves             [L, M, S, XL]
Handbag            [S, XL, M, L]
Hat                [M, L, S, XL]
Headphones    [S, M, nan, L, XL]
Hoodie             [M, L, S, XL]
Jacket             [L, S, M, XL]
Jeans              [L, M, XL, S]
Jewelry            [L, XL, M, S]
Laptop        [nan, M, S, XL, L]
Pants              [L, M, XL, S]
Phone         [nan, L, S, M, XL]
Sandals            [M, S, L, XL]
Scarf              [M, L, S, XL]
Shirt         [M, XL, L, S, nan]
Shoes         [M, L, nan, XL, S]
Shorts             [S, M, L, XL]
Skirt              [S, L, M, XL]
Sneakers           [S, M, L, XL]
Socks              [M, XL, L, S]
Sunglasses         [M, L, S, XL]
Sweater            [M, S, L, XL]
T-shirt            [XL, M, S, L]
Watch         [nan, M, L, XL, S]
Name: Size, dtype: object

In [303]:
#replacing the null values in electronics using loc
df.loc[df['Category']=='Electronics','Size'] = "Not Applicable"

In [305]:
df.groupby('Category')['Size'].unique()

Category
Accessories    [M, L, S, XL, nan]
Clothing       [XL, M, S, L, nan]
Electronics      [Not Applicable]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [307]:
#replacing the null values in accessories using loc
df.loc[df['Category']=='Accessories','Size'] = "Free size"

In [309]:
df.groupby('Category')['Size'].unique()

Category
Accessories           [Free size]
Clothing       [XL, M, S, L, nan]
Electronics      [Not Applicable]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [311]:
#replacing the null values in footwear using loc
df.loc[df['Category']=='Footwear','Size'] = "Not Available"

In [313]:
df.groupby('Category')['Size'].unique()

Category
Accessories           [Free size]
Clothing       [XL, M, S, L, nan]
Electronics      [Not Applicable]
Footwear          [Not Available]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [315]:
#replacing the null values in clothing using loc
df.loc[
    (df['Category'] == 'Clothing') & (df['Size'].isnull()),
    'Size'
] = df[df['Category'] == 'Clothing']['Size'].mode()[0]

In [317]:
df.groupby('Category')['Size'].unique()

Category
Accessories         [Free size]
Clothing          [XL, M, S, L]
Electronics    [Not Applicable]
Footwear        [Not Available]
Outerwear         [XL, L, S, M]
Name: Size, dtype: object

Cleaning Review rating

In [320]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free size,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free size,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free size,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [322]:
df['Review Rating'].mean()

np.float64(3.668195100022477)

In [324]:
df['Review Rating'].median()

3.7

In [326]:
df['Review Rating'].mode()

0    4.0
Name: Review Rating, dtype: float64

In [328]:
df.groupby('Item Purchased')['Review Rating'].mean()

Item Purchased
Backpack      3.758333
Bag           3.168539
Belt          3.762963
Blouse        3.677647
Boots         3.813194
Coat          3.721875
Dress         3.750000
Gloves        3.862774
Handbag       3.771975
Hat           3.796753
Headphones    3.075949
Hoodie        3.716779
Jacket        3.761446
Jeans         3.651969
Jewelry       3.761850
Laptop        3.191176
Pants         3.720833
Phone         2.939024
Sandals       3.837037
Scarf         3.702564
Shirt         3.427273
Shoes         3.546154
Shorts        3.722981
Skirt         3.779747
Sneakers      3.757931
Socks         3.755063
Sunglasses    3.745679
Sweater       3.768712
T-shirt       3.790541
Watch         3.100000
Name: Review Rating, dtype: float64

In [330]:
#replacing null values of review ratings by the mean of each item purchased
df['Review Rating']=df['Review Rating'].fillna(df.groupby('Item Purchased')['Review Rating'].transform('mean'))

In [332]:
df['Review Rating']=df['Review Rating'].round(2)

Cleaning previous purchases

In [335]:
df['Previous Purchases']=df['Previous Purchases'].fillna(0)

In [337]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases          0
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [250]:
#df.drop(columns='size', inplace=True)

KeyError: "['size'] not found in axis"

In [339]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases          0
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [343]:
df[df['Size'].isnull()]['Category'].value_counts()

Series([], Name: count, dtype: int64)

In [345]:
df.loc[
    (df['Category'] == 'Accessories') & (df['Size'].isnull()),
    'Size'
] = 'Free Size'

In [347]:
df.groupby("Item Purchased")['Purchase Amount (USD)'].mean()

Item Purchased
Backpack       60.111111
Bag           735.773625
Belt           59.993902
Blouse         60.802326
Boots          62.616438
Coat           57.851852
Dress          62.168675
Gloves         60.550000
Handbag        57.987261
Hat            60.787097
Headphones    831.344565
Hoodie         58.059603
Jacket         56.777108
Jeans          60.456693
Jewelry        59.011494
Laptop        805.502027
Pants          59.005848
Phone         734.477349
Sandals        57.527607
Scarf          61.157233
Shirt         279.935608
Shoes         276.343790
Shorts         60.073620
Skirt          59.723270
Sneakers       59.551724
Socks          58.188679
Sunglasses     59.975610
Sweater        57.638554
T-shirt        63.093333
Watch         685.231471
Name: Purchase Amount (USD), dtype: float64

In [349]:
df.groupby("Item Purchased")['Purchase Amount (USD)'].median()

Item Purchased
Backpack       59.000
Bag           766.850
Belt           59.500
Blouse         61.500
Boots          65.500
Coat           55.000
Dress          63.500
Gloves         61.500
Handbag        57.000
Hat            62.000
Headphones    854.555
Hoodie         57.000
Jacket         55.000
Jeans          61.000
Jewelry        57.000
Laptop        826.425
Pants          59.000
Phone         736.010
Sandals        58.000
Scarf          64.000
Shirt          78.000
Shoes          78.000
Shorts         61.000
Skirt          61.000
Sneakers       59.000
Socks          55.000
Sunglasses     61.500
Sweater        56.000
T-shirt        64.500
Watch         641.485
Name: Purchase Amount (USD), dtype: float64

In [353]:
df['Purchase Amount (USD)']=df['Purchase Amount (USD)'].fillna(df.groupby('Item Purchased')['Purchase Amount (USD)'].transform('mean'))

In [355]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [357]:
#duplicates check
df.duplicated().sum()

np.int64(50)

In [359]:
df[df.duplicated()]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
886,2834,43,Female,Jeans,Clothing,56.0,Arkansas,M,Teal,Fall,3.30,No,Free Shipping,No,19.0,Cash,Monthly
1402,1621,25,Male,Hat,Accessories,47.0,Virginia,Free size,Charcoal,Winter,3.10,No,2-Day Shipping,Yes,27.0,PayPal,Every 3 Months
1509,974,60,Male,Jacket,Outerwear,75.0,Colorado,M,Teal,Fall,3.50,Yes,2-Day Shipping,Yes,30.0,Bank Transfer,Quarterly
1600,2135,55,Male,Sandals,Footwear,41.0,Virginia,Not Available,Maroon,Winter,2.90,No,Standard,No,35.0,Credit Card,Fortnightly
1665,1846,51,Male,Sandals,Footwear,78.0,Delaware,Not Available,Orange,Winter,2.80,No,2-Day Shipping,No,39.0,Bank Transfer,Quarterly
1797,3639,40,Female,Backpack,Accessories,20.0,Kansas,Free size,Olive,Spring,4.60,No,Express,No,50.0,PayPal,Bi-Weekly
1870,3456,49,Female,T-shirt,Clothing,89.0,Ohio,M,Orange,Fall,4.70,No,Standard,No,13.0,Venmo,Annually
2033,1812,42,Male,Belt,Accessories,77.0,Wisconsin,Free size,Blue,Summer,3.60,No,Standard,No,33.0,Bank Transfer,Annually
2113,3040,59,Female,Blouse,Clothing,48.0,Alabama,L,Blue,Spring,3.20,No,Next Day Air,No,31.0,PayPal,Bi-Weekly
2226,1371,27,Male,Scarf,Accessories,67.0,Montana,Free size,Peach,Summer,3.70,No,2-Day Shipping,Yes,41.0,Bank Transfer,Every 3 Months
2358,2977,30,Female,Coat,Outerwear,97.0,Nebraska,M,Silver,Summer,2.80,No,Express,No,28.0,Cash,Fortnightly
2447,2678,45,Female,Shorts,Clothing,43.0,Connecticut,L,Olive,Spring,3.80,No,Next Day Air,No,6.0,PayPal,Every 3 Months
2630,992,20,Male,Shorts,Clothing,97.0,Wisconsin,XL,White,Spring,2.70,Yes,Standard,Yes,40.0,Bank Transfer,Bi-Weekly
2642,1566,58,Male,Sunglasses,Accessories,93.0,Idaho,Free size,Peach,Fall,4.20,No,Free Shipping,Yes,48.0,PayPal,Annually
2739,2227,22,Male,Shirt,Clothing,72.0,Missouri,L,Blue,Spring,4.80,No,Store Pickup,No,28.0,Cash,Annually
2740,3487,51,Female,Shorts,Clothing,89.0,North Carolina,L,Charcoal,Winter,4.90,No,Standard,No,6.0,PayPal,Weekly
2800,2069,70,Male,Jewelry,Accessories,81.0,Vermont,Free size,Black,Summer,3.90,No,Store Pickup,No,44.0,Venmo,Monthly
2905,2158,41,Male,Handbag,Accessories,68.0,Mississippi,Free size,Turquoise,Winter,4.00,No,Next Day Air,No,41.0,Venmo,Fortnightly
2922,3334,55,Female,Jeans,Clothing,35.0,Minnesota,M,Violet,Spring,4.20,No,Express,No,3.0,PayPal,Monthly
3036,258,20,Male,Handbag,Accessories,53.0,West Virginia,Free size,Red,Summer,4.50,Yes,Express,Yes,5.0,Credit Card,Quarterly
3065,3887,37,Female,Jewelry,Accessories,92.0,Iowa,Free size,Brown,Summer,3.90,No,Express,No,40.0,Debit Card,Quarterly
3185,1609,26,Male,Sandals,Footwear,58.0,Nebraska,Not Available,Cyan,Fall,4.60,No,Next Day Air,Yes,12.0,Bank Transfer,Bi-Weekly
3357,3091,29,Female,Shirt,Clothing,36.0,Texas,M,Peach,Summer,4.90,No,Store Pickup,No,15.0,Bank Transfer,Quarterly
3390,603,37,Male,Shoes,Footwear,58.0,Oregon,Not Available,Lavender,Summer,4.20,Yes,Next Day Air,Yes,10.0,Cash,Every 3 Months
3538,1698,36,Male,Shirt,Clothing,87.0,South Carolina,L,Lavender,Fall,3.50,No,Next Day Air,No,48.0,Credit Card,Every 3 Months
3683,1209,20,Male,Boots,Footwear,100.0,Wisconsin,Not Available,Red,Winter,3.81,No,2-Day Shipping,Yes,8.0,Debit Card,Annually
3698,172,29,Male,Shorts,Clothing,35.0,Virginia,M,Blue,Summer,3.60,Yes,Store Pickup,Yes,4.0,Credit Card,Weekly
3742,323,41,Male,Belt,Accessories,95.0,Tennessee,Free size,Cyan,Winter,3.00,Yes,Standard,Yes,47.0,Credit Card,Monthly
3810,2429,65,Male,T-shirt,Clothing,38.0,Idaho,M,Violet,Spring,4.40,No,Next Day Air,No,34.0,Debit Card,Annually
3843,615,68,Male,Jewelry,Accessories,85.0,Idaho,Free size,Lavender,Winter,4.00,Yes,Standard,Yes,21.0,Credit Card,Bi-Weekly
3961,2558,70,Male,Shorts,Clothing,23.0,Oklahoma,L,Cyan,Spring,3.90,No,Standard,No,17.0,PayPal,Fortnightly
3987,3507,18,Female,Shirt,Clothing,57.0,Illinois,L,Olive,Winter,3.70,No,2-Day Shipping,No,12.0,Cash,Fortnightly
4050,3287,45,Female,Jacket,Outerwear,67.0,Illinois,L,Pink,Winter,5.00,No,Express,No,4.0,Venmo,Fortnightly
4059,227,29,Male,Shoes,Footwear,74.0,Texas,Not Available,Violet,Spring,3.30,Yes,Free Shipping,Yes,5.0,PayPal,Monthly
4131,2642,25,Male,Sunglasses,Accessories,60.0,Vermont,Free size,Olive,Winter,2.70,No,Next Day Air,No,20.0,Bank Transfer,Every 3 Months
4183,1523,38,Male,Shorts,Clothing,72.0,Tennessee,L,Yellow,Spring,4.80,No,Free Shipping,Yes,5.0,Debit Card,Monthly
4330,3716,63,Female,Sunglasses,Accessories,34.0,Nebraska,Free size,Orange,Fall,3.40,No,Free Shipping,No,2.0,Bank Transfer,Monthly
4390,3846,58,Female,Sweater,Clothing,52.0,California,M,Green,Winter,4.90,No,Standard,No,46.0,Venmo,Annually
4445,3644,53,Female,Scarf,Accessories,96.0,Tennessee,Free size,Magenta,Fall,3.20,No,Standard,No,47.0,Debit Card,Annually
4468,473,20,Male,Jeans,Clothing,39.0,Georgia,L,Gray,Winter,3.90,Yes,Free Shipping,Yes,3.0,Bank Transfer,Quarterly
4513,1317,28,Male,Belt,Accessories,32.0,Arkansas,Free size,Lavender,Spring,4.60,No,Standard,Yes,14.0,Debit Card,Bi-Weekly
4558,3339,29,Female,Skirt,Clothing,94.0,Minnesota,L,White,Winter,2.90,No,2-Day Shipping,No,46.0,Credit Card,Monthly
4595,3577,29,Female,Boots,Footwear,24.0,Maine,Not Available,Yellow,Spring,3.00,No,Express,No,12.0,Venmo,Bi-Weekly
4664,2689,53,Female,Handbag,Accessories,63.0,West Virginia,Free size,Turquoise,Spring,2.90,No,2-Day Shipping,No,18.0,Credit Card,Every 3 Months
4717,2800,23,Female,T-shirt,Clothing,89.0,Maine,L,Pink,Spring,3.90,No,Free Shipping,No,9.0,Bank Transfer,Every 3 Months
4735,2182,22,Male,Handbag,Accessories,63.0,Hawaii,Free size,Black,Fall,3.20,No,Free Shipping,No,32.0,Bank Transfer,Bi-Weekly
4841,2622,48,Male,Shoes,Footwear,46.0,Maine,Not Available,Beige,Winter,3.00,No,Express,No,21.0,Bank Transfer,Annually
4887,3875,70,Female,Sweater,Clothing,54.0,Nevada,XL,Beige,Summer,3.90,No,2-Day Shipping,No,33.0,Credit Card,Bi-Weekly
4901,1060,22,Male,Jacket,Outerwear,34.0,North Carolina,M,Beige,Winter,2.50,No,Standard,Yes,25.0,Debit Card,Monthly
5037,3439,26,Female,Shirt,Clothing,71.0,Kentucky,M,Violet,Fall,3.00,No,Store Pickup,No,33.0,Credit Card,Monthly

#deleting duplicates

In [361]:
len(df)

5050

In [363]:
df = df.drop_duplicates(subset = ['Customer ID'], keep = 'first')

In [365]:
df.duplicated().sum()

np.int64(0)

Rename the Headers

In [367]:
df.columns = df.columns.str.replace(" ", "_")

In [369]:
df.head()

,Customer_ID,Age,Gender,Item_Purchased,Category,Purchase_Amount_(USD),Location,Size,Color,Season,Review_Rating,Subscription_Status,Shipping_Type,Discount_Applied,Previous_Purchases,Payment_Method,Frequency_of_Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free size,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free size,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free size,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [411]:
df.columns = df.columns.str.lower()

In [417]:
#renaming the purchase_amount_(usd) column
df = df.rename(columns={"purchase_amount_(usd)": "purchase_amount"})

In [419]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free size,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free size,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free size,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

SQL SERVER CONNECCTION

In [200]:
!pip install mysql-connector-python sqlalchemy pandas
import mysql.connector
from sqlalchemy import create_engine
import pandas as pd

Requirement already satisfied: mysql-connector-python in /Applications/anaconda3/lib/python3.13/site-packages (9.7.0)
Requirement already satisfied: sqlalchemy in /Applications/anaconda3/lib/python3.13/site-packages (2.0.39)
Requirement already satisfied: pandas in /Applications/anaconda3/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /Applications/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: numpy>=1.26.0 in /Applications/anaconda3/lib/python3.13/site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Applications/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Applications/anaconda3/lib/python3.13/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Applications/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Applications/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [202]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+mysqlconnector://root:@localhost/customer_analysis"
)

print("Connection Successful!")

Connection Successful!

In [34]:
table_name = "customers"

df.to_sql(
    table_name,
    con=engine,
    if_exists="replace",
    index=False
)

print("Data successfully loaded into MySQL!")

Data successfully loaded into MySQL!

In [54]:
print(df.columns)

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [56]:
df.to_sql(
    "customers",
    con=engine,
    if_exists="replace",
    index=False
)

print("Updated table uploaded successfully!")

Updated table uploaded successfully!

In [58]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [421]:
df.to_csv("customers.csv", index=False)

In [423]:
import os
os.getcwd()

'/Users/gulkapoor/DataAnalysisProjects'

In [425]:
os.listdir()

['customers.csv',
 '.DS_Store',
 'customer_behaviour.csv',
 '3_PersonalFinance',
 'README.md',
 'download_help.png',
 '2_SalesInsightsTableau',
 'Data-Analytics-Projects',
 '.gitignore',
 '4_HRAnalytics',
 'customer behaviour analysis.ipynb',
 '.ipynb_checkpoints',
 '1_SalesInsights',
 '.git',
 '5_CricketT20Analytics']

In [395]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free size,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free size,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free size,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly